// Generated by CoffeeScript 1.8.0
(function() {
  var Tasks;

  Tasks = new Mongo.Collection('tasks');

  if (Meteor.isClient) {
    Template.body.helpers({
      tasks: function() {
        return Tasks.find({}, {
          sort: {
            createdAt: -1
          }
        });
      }
    });
    Template.body.events({
      'submit .new-task': function(e) {
        var text;
        e.preventDefault();
        console.log('e.target', e.target);
        text = e.target.text.value;
        Tasks.insert({
          text: text,
          createdAt: new Date
        });
        return e.target.text.value = '';
      }
    });
  }

}).call(this);
